HH-217811 use detailed output only for current violations
hhru/checkstyle pull request #25
Opened 2024-05-30 13:01 UTC by dzharikhin

На монолите сборка проходит
> [!IMPORTANT] 
> Добавь в описание PR changelog в формате:

- [ ] **version change** : PATCH
- [ ] **description**: 'детализация нарушений чека chaincall'
- [ ] **requires_changes_in_hh** : false
- [ ] **instructions** :

2024-05-31 12:25 UTC, Sparkymann commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +    return TokenUtil.isOfType(childAst, TokenTypes.METHOD_CALL) && !TokenUtil.isOfType(childAst.getParent(), TokenTypes.TYPECAST);
как-то помешает TYPECAST при логировании?

2024-06-03 12:10 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +    return TokenUtil.isOfType(childAst, TokenTypes.METHOD_CALL) && !TokenUtil.isOfType(childAst.getParent(), TokenTypes.TYPECAST);
ловил багу что `((A) b.c()).d()` срабатывает на `c()`. поэтому да

2024-06-03 14:51 UTC, dzharikhin commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "18:16: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
я честно не знаю, что за allowUnwrappedFirstCall 
у меня вроде получился дифф в один лог 148:18

2024-06-03 14:55 UTC, pvorlov commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "18:16: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
https://github.com/hhru/checkstyle/blob/a5961209f54027778507298c3d2fc137c5e8e7df/checkstyle-config-plugin/src/main/resources/shared-checkstyle.xml#L52

Теперь надо уметь работать в двух режимах.
Если `allowUnwrappedFirstCall` до допускается код:
```
Set.of(1,2,3)
    .stream()
    .filter()
    .toList()
```

2024-06-03 14:55 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +    return TokenUtil.isOfType(childAst, TokenTypes.METHOD_CALL) && !TokenUtil.isOfType(childAst.getParent(), TokenTypes.TYPECAST);
да щас проще выпилить - будем надеяться, что покуда оно под violate запускается, то он защитит уже от фолс позитивов

2024-06-03 14:58 UTC, dzharikhin commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "18:16: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
ну как будто 148:18 - то что нужно. других пометок в тестовом классе вроде и нет

2024-06-03 16:35 UTC, pvorlov requested changes

2024-06-03 16:35 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +          currentLineOuterMostMethod = child;
Т.е. если child не метод мы записываем его в переменную метод?
Давай тогда уберём суффикс метод из переменной чтобы она с толку не сбивала.

2024-06-03 16:35 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +          if (methodCallCount > 1) {
Cтрочкой выше `methodCallCount++` а в других местах везде единицы присваиваются.
Разве оно не всегда `true`?

2024-06-03 16:35 UTC, pvorlov commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "64:18: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
Не хватает примерно 74:29 (вторая цифра +-1)

2024-06-03 16:35 UTC, pvorlov commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "63:9: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
Здесь и дальше в аналогичных местах: при включенном `allowUnwrappedFirstCall"` 63 строка не причина ошибки, её не надо выводить

2024-06-03 16:37 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
А почему boolean?
Если обход дерева вернул false разве это не значит, что в алгоритме ошибка?

2024-06-03 17:11 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
ну обратная совместимость же. даже если ошибка надо не падать, а возвращать то, шо раньше возвращало

2024-06-03 17:13 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +    DetailAST methodCallDescendant = child.getFirstChild();
а есть где-то доки как этот парсер вообще работает? я так и не осознал до конца какая у него иерархия токенов вообще

2024-06-04 09:40 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +    DetailAST methodCallDescendant = child.getFirstChild();
Я не видел. Методом проб и ошибок.
Как генерить дерево есть в примере про xpath: https://checkstyle.sourceforge.io/checks/coding/matchxpath.html#MatchXpath

2024-06-04 09:46 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
Текущий алгоритм вроде не даёт ложно-положительных срабатываний (что-то не замечает, тут да).
По идее если сюда попали, то что-то да писать точно надо

2024-06-05 15:42 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +        && TokenUtil.areOnSameLine(methodCallDescendant.findFirstToken(TokenTypes.RPAREN), child);
задумка была в том, чтобы в первом случае - ругаться, во втором - не ругаться, т.к. продолжение чейна с новой строки

2024-06-05 15:56 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
ровн это в коде и написано. если че-то мы по каким-то причинам не нашли - надо что-то все равно в ошибку вывести

2024-06-05 17:11 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +    DetailAST methodCallDescendant = child.getFirstChild();
приемлемо. если прижмет распечатаю покурю как он парсит-то хоть.
пока видимо верну метод выпиленный - там как-то типы ограничивались

2024-06-07 13:54 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
Предлагаю всегда находить если мы точно нашли ошибку (попали в violate)

2024-06-07 14:03 UTC, pvorlov commented on checks/src/test/resources/ru/hh/checkstyle/WrapNewLinesMethodChainCallCheckTestInput.java
> +    //expression with static method - NOT OK or OK depending on "allowUnwrappedFirstCall" property
```suggestion
    //expression with static method - NOT OK but firstCall is OK depending on "allowUnwrappedFirstCall" property
```

Предлагаю также как и ниже, ведь сам violation всё-таки должен возникнуть

2024-06-07 14:21 UTC, pvorlov commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "63:9: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
74:29 всё ещё лишний

2024-06-07 14:32 UTC, pvorlov commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "63:9: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
отсальные вроде ок, только 74:29

2024-06-10 09:01 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
гарантировать это нельзя - не хочу рисковать, чтобы не вылезло где-то несовместимое опять

2024-06-10 09:12 UTC, dzharikhin commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "63:9: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
лишний? там же получается 2 вызова - конструктор и следующий. как будто allowUnwrappedFirstCall тут погоды не делает. или мы конструктор тоже считаем "особенным"?

2024-06-11 13:36 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
Оно же не повлияет на совместимость с точки зрения дополнительных violation.
В худшем случае пропускать будет.

2024-06-11 13:41 UTC, dzharikhin commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +      if (!tryLogViolationDetails(methodCall)) {
релиз не сломается, да

2024-06-11 13:47 UTC, pvorlov commented on checks/src/test/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheckTest.java
> +        "63:9: " + getCheckMessage(WRAPPED_CHAIN_MSG_KEY),
Нет никакой разницы конструктор, метод или переменная.
С точки зрения текущего алгоритма это всё [caller](https://github.com/hhru/checkstyle/blob/master/checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java#L85)
Да, это 2 вызова и точка между ними. И вот `allowUnwrappedFirstCall` как раз говорит что между первыми 2 участниками чейна (вызовами, конструкторами, переменными, не важно) не обязательно делать wrap.
А раз необязательно - не нужно подсвечивать эту строку.

2024-06-11 17:38 UTC, pvorlov requested changes
С работоспособностью вроде разобрались но есть существенные проблемы с читабельностью.
Все комментарии примерно про одно.

2024-06-11 17:38 UTC, pvorlov commented on checks/src/main/java/ru/hh/checkstyle/WrapNewLinesMethodChainCallsCheck.java
> +          || isCallAfterMultilineCall(child)
Ну костыль же, из-за которого разобраться что здесь происходит нужно много и много часов.
Тот самый случай когда минус на минус дал плюс и юнит тесты прошли.
По факту у тебя ошибка в коде двумя строчками ниже:
`if (TokenUtil.areOnSameLine(currentLineOuterMostMethodCaller, child)`
здесь сравнивается, что на одинаковой строчке находятся открывающие скобки (для методов).
А по хорошему должно было быть что-то вроде
`if (TokenUtil.areOnSameLine(findChainCallStart(currentLineOuterMostMethodCaller), findChainCallEnd(child))`
если сделать проверку в таком виде то `isCallAfterMultilineCall(child)` можно будет удалить

2024-06-25 16:05 UTC, pvorlov reviewed
Код стал намного чище, спасибо.
Прогони, пожалуйста, checkstyle c checkstyle - ругается на отступы

2024-06-26 08:35 UTC, pvorlov approved these changes

2024-07-01 10:47 UTC, merged